version: '3.5'

services:
  api:
    build:
      context: ./api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./api:/app

  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq/rabbitmq_plugins:/etc/rabbitmq/enabled_plugins

  php:
    build:
      context: ./php
    entrypoint: 'tail -f /dev/null'
    volumes:
      - ./php:/app

  perl:
    build:
      context: ./perl
    entrypoint: 'tail -f /dev/null'
    volumes:
      - ./perl:/app


  python:
    build:
      context: ./python
    entrypoint: 'tail -f /dev/null'
    volumes:
      - ./python:/app